image: python:3.9-slim

stages:
  - build
  - deploy

build:
  stage: build
  script:
    - pip install -r requirements.txt
    - docker build -t my-app .
  artifacts:
    paths:
      - docker-compose.yml

deploy:
  stage: deploy
  script:
    - docker run -p 8080:8080 my-app
  environment:
    DOCKER_HOST: tcp://localhost:2375
